version: '3.8'

services:
  web:
    image: ouroboros-web
    build: .
    container_name: ouroboros-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
